# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [7]:
print(np.__version__)
np.__config__.show()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MKK1111999/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/MKK1111999/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MKK1111999/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [9]:
Z = np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
# python -c "import numpy as np; np.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
arr = np.arange(10,50)
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.18470594 0.39805802 0.59522563]
  [0.24506402 0.4002657  0.39289149]
  [0.82419154 0.0903822  0.8100534 ]]

 [[0.63507753 0.96212869 0.36522562]
  [0.27098086 0.31337816 0.78446331]
  [0.74341366 0.08628625 0.57595887]]

 [[0.60566356 0.01146752 0.62418475]
  [0.52776172 0.55442215 0.62002145]
  [0.54388449 0.67296502 0.32316723]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr = np.random.random((10,10))
arr_min,arr_max = arr.min(),arr.max()
print(arr_min,arr_max)

0.021677827283632656 0.9862576401740976


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
arr = np.random.random(30)
print(arr.mean())

0.5541800179047781


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
arr = np.ones((5,5))
arr = np.pad(arr,pad_width =1,mode = 'constant',constant_values = 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [27]:
arr = np.random.random((5,5))
arr = (arr-arr.mean())/(arr.std())
print(arr)

[[-0.80082383 -0.39348099  1.71147573 -0.43860162 -0.93237016]
 [ 0.81041068  1.11518578 -1.59011492 -0.51800648 -1.84927911]
 [ 0.44909085 -0.50712053  1.1736691   1.58029702 -0.84334143]
 [ 1.22606563 -0.73613915  0.38736761  0.19770216  1.04024271]
 [ 1.14592563 -0.42250407 -1.39839937  0.11620507 -0.52345631]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [28]:
arr = np.dtype([("r",np.ubyte,1),
               ("g",np.ubyte,1),
               ("b",np.ubyte,1),
               ("a",np.ubyte,1)])
print(arr)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-28-fffd26271fdb>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.dtype([("r",np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
arr = np.dot(np.ones((5,3)),np.ones((3,2)))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
arr = np.arange(11)
arr[(3<arr) & (arr<=8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
from numpy import *
print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
Z=np.arange(3,4)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[3]
[27]
[4]
[False]
[0.+3.j]
[3.]
[False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-33-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-33-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [34]:
arr= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)),arr))

[ 4. -3.  8.  9. -9.  5.  3. -8. -3. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [35]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[2 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [36]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]
[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [37]:
print( np.sqrt(-1))

nan


<ipython-input-37-609404d822cc>:1: RuntimeWarning: invalid value encountered in sqrt
  print( np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(np.datetime64('today', 'D'))
print(np.timedelta64(1, 'D'))

2020-08-04
2020-08-05
1 days


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [39]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [40]:
A=np.ones(3)*1
B=np.random.rand(3)*2
np.multiply(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-0.74688018 -0.33833017 -0.78316301]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [41]:
Z= np.random.uniform(0,10,10)
print(np.trunc(Z))
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))

[9. 7. 0. 3. 5. 8. 3. 8. 2. 8.]
[9. 7. 0. 3. 5. 8. 3. 8. 2. 8.]
[9. 7. 0. 3. 5. 8. 3. 8. 2. 8.]
[9. 7. 0. 3. 5. 8. 3. 8. 2. 8.]
[9 7 0 3 5 8 3 8 2 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
arr = np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
def generator():
    for x in range(10):
        yield x
Z = np.fromiter(generator(),dtype = int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [44]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.02036492 0.245402   0.29728971 0.39125739 0.44599135 0.55699225
 0.66870675 0.7793377  0.95003859 0.95733825]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [46]:
arr = np.random.random(10)
print(np.add.reduce(arr))

5.465923690371444


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[1 1 0 1 0]
[0 1 0 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
arr = np.zeros(10)
arr.flags.writeable = False
# arr[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [49]:
arr = np.random.random((10,2))
x,y = arr[:,0],arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.23631715 0.61828425 0.67322112 0.52046095 1.16033131 0.79835332
 0.84813496 0.73028135 1.09571916 0.63362478]
[0.67139717 0.75696795 1.29820946 1.55852895 0.75112366 0.39664565
 0.18276625 0.89409414 0.81076823 0.86745066]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
arr = np.random.random(10)
print(arr.argmax())
arr_max = arr.max()
index = np.where(arr==arr_max)
arr[index]=0
print(arr)

3
[0.08568064 0.17325007 0.87225663 0.         0.8456534  0.0256742
 0.91613655 0.54249519 0.54541572 0.79605603]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [51]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [52]:
x=np.arange(8)
print(x)
y=x+0.5
print(y)
c = 1.0/np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c))

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


In [53]:
import numpy as np

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [54]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).max)
    print(np.iinfo(dtype).min)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).eps)

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.1920929e-07
1.7976931348623157e+308
-1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [55]:
np.set_printoptions()
Z=np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [56]:
arr = np.arange(100)
value = np.random.uniform(0,100)
index = (np.abs(arr-value)).argmin()
print(arr[index])

20


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [57]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-57-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [58]:
# Z = np.random.random((10,2))
# X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.31904467 0.28588442 0.59198141 0.82056137 0.90672815
  0.14120695 1.07329403 0.93485692 0.57786763]
 [0.31904467 0.         0.26651771 0.65667241 0.52840569 0.82613275
  0.26125899 0.96011192 0.93167997 0.34095846]
 [0.28588442 0.26651771 0.         0.39307801 0.60208966 0.63211806
  0.14479567 0.79227768 0.69446782 0.33053184]
 [0.59198141 0.65667241 0.39307801 0.         0.81319638 0.41665781
  0.48011538 0.59862679 0.35542465 0.5570297 ]
 [0.82056137 0.52840569 0.60208966 0.81319638 0.         0.68801379
  0.7093311  0.72269829 0.89477833 0.27764628]
 [0.90672815 0.82613275 0.63211806 0.41665781 0.68801379 0.
  0.76901067 0.18245264 0.23030881 0.54921975]
 [0.14120695 0.26125899 0.14479567 0.48011538 0.7093311  0.76901067
  0.         0.9334447  0.81030841 0.45206974]
 [1.07329403 0.96011192 0.79227768 0.59862679 0.72269829 0.18245264
  0.9334447  0.         0.35191587 0.65053554]
 [0.93485692 0.93167997 0.69446782 0.35542465 0.89477833 0.23030881
  0.81030841 0.35191

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [59]:
arr = np.arange(10,dtype = np.float32)
arr = arr.astype(np.int32,copy =False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [60]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n
            """)
arr_of_strings = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(arr_of_strings)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
arr = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(arr):      #method1
    print(index,value)
for index in np.ndindex(arr.shape):         #method2
    print(index,arr[index])
for index in range(len(arr)):               #method3
    for j in range(len(arr[index])):
        print((index,j),arr[index][j])
for index,value in enumerate(arr):         #method4
    for val in enumerate(value):
        print((index,val[:][0]),val[:][1])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [62]:
x,y = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
d = np.sqrt(x**2+y**2)
mu,sigma = 0.0,1.0
G = np.exp(-((d-mu)**2)/(2*sigma**2))
print(G)

[[1.         0.96923323 0.8824969  0.7548396  0.60653066]
 [0.96923323 0.93941306 0.85534533 0.73161563 0.58786967]
 [0.8824969  0.85534533 0.77880078 0.66614361 0.53526143]
 [0.7548396  0.73161563 0.66614361 0.56978282 0.45783336]
 [0.60653066 0.58786967 0.53526143 0.45783336 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [63]:
n=5
p=3
arr = np.zeros((n,n))
print(np.random.choice(range(n*n),p,replace = False))
np.put(arr,np.random.choice(range(n*n),p,replace = False),1)
print(arr)

[ 9 18 19]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [64]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1,keepdims=True)
print(x)
print(y)

[[0.6631207  0.25671334 0.75776917 0.63770368 0.48770393 0.83928016
  0.8779258  0.52601125 0.0395846  0.44183508]
 [0.69913249 0.96232376 0.12776784 0.86989537 0.63915593 0.24963587
  0.50053242 0.80566479 0.63053133 0.41663519]
 [0.76570486 0.71874813 0.16038249 0.14356275 0.23033125 0.88887984
  0.56667907 0.10877735 0.04438569 0.31086331]
 [0.04579598 0.22870045 0.69534753 0.0020329  0.41105986 0.05574326
  0.45044298 0.92444379 0.78553904 0.3466399 ]
 [0.9882983  0.69862504 0.87787715 0.03828489 0.80285598 0.10559322
  0.01100864 0.94440728 0.23695025 0.25690855]]
[[ 0.11035592 -0.29605143  0.20500439  0.08493891 -0.06506084  0.28651539
   0.32516103 -0.02675352 -0.51318017 -0.11092969]
 [ 0.10900499  0.37219626 -0.46235966  0.27976787  0.04902843 -0.34049162
  -0.08959508  0.21553729  0.04040383 -0.17349231]
 [ 0.37187339  0.32491665 -0.23344898 -0.25026872 -0.16350022  0.49504837
   0.17284759 -0.28505412 -0.34944579 -0.08296816]
 [-0.34877859 -0.16587412  0.30077296 -0.39254167

#### 59. How to sort an array by the nth column? (★★☆)

In [65]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 9 8]
 [1 2 5]
 [7 8 6]]
[[1 2 5]
 [7 8 6]
 [5 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [66]:
arr = np.random.randint(0,3,(3,10))
print(arr)
print(~arr.any(axis=0))
print((~arr.any(axis=0)).any())

[[2 1 0 0 1 2 0 2 2 0]
 [2 1 0 1 0 2 2 1 2 1]
 [0 2 1 1 1 1 1 2 0 1]]
[False False False False False False False False False False]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [67]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4800792688584541


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [68]:
import numpy as np

In [69]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [70]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [71]:
Z= np.ones(10)
I = np.random.randint(0,len(Z),20)                   
Z += np.bincount(I, minlength=len(Z))                #method1 using np.bincount
print(Z)
unique,count = np.unique(I,return_counts = True)     #method2 using np.unique
# print(np.asarray((unique,count)))
print(count+1)

[2. 5. 2. 1. 2. 3. 3. 3. 3. 6.]
[2 5 2 2 3 3 3 3 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [72]:
X = [1,2,3,4,5,6]
I = np.arange(6)
F = np.bincount(I,X)       #elements of X acts as weights
print(F)

[1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [73]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# print(I[...,1])
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
# print(F[...])
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [74]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
# print(A.shape[:-2] + (-1,))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
# print(A.reshape(A.shape[:-2] + (-1,)))

[[31 67 62 53]
 [44 68 64 68]
 [60 59 59 48]]
[[31 67 62 53]
 [44 68 64 68]
 [60 59 59 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [75]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.41739329 0.44191384 0.5605077  0.40599793 0.51779493 0.50248644
 0.57464717 0.42943357 0.45597766 0.4568306 ]
0    0.417393
1    0.441914
2    0.560508
3    0.405998
4    0.517795
5    0.502486
6    0.574647
7    0.429434
8    0.455978
9    0.456831
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [76]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[0.67386815 2.19285473 0.60543607 1.29522416 0.79901961]
[0.67386815 2.19285473 0.60543607 1.29522416 0.79901961]
[0.67386815 2.19285473 0.60543607 1.29522416 0.79901961]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [77]:
arr = np.array([1,2,3,4,5])
shift = 3
ans = np.zeros(len(arr)+(len(arr)-1)*shift)
ans[::shift+1]=arr
print(ans)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [78]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [79]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)